workspace:
  base: /go
  path: src/github.com/gboddin/sembump

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure 
      - go build
